import { Typography } from "@mui/material";
import Head from "next/head";
import BaseLayout from "~/components/BaseLayout";

export default function Home() {
  return (
    <>
      <Head>
        <title>YTM ROVERS</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BaseLayout pageIndex={0} >
      <main >
          <div>
            <Typography variant="h5">YTM ROVERS LANDING PAGES</Typography>
          </div>
      </main>
      </BaseLayout>
    </>
  )   
}


