import {  useSession } from "next-auth/react";
import Head from "next/head";
import { api } from "~/utils/api";
import { Button, Link } from "@mui/material";
import BaseLayout from "~/components/VolunteerBaseLayout";

export default function Home() {


  return (
    <>
      <Head>
        <title>YTM ROVERS</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BaseLayout pageIndex={0} >
      <main >
          <div>
        <Button variant="contained" color="primary">
          <Link href="/page">
            Go to Page
          </Link>
        </Button>
          </div>
      </main>
      </BaseLayout>
    </>
  )   
}


