import { Typography } from "@mui/material";
import Head from "next/head";
import BaseLayout from "~/components/BaseLayout";

export default function Home() {
  return (
    <>
      <Head>
        <title>YTM ROVERS</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/logo2.png" />
      </Head>
      <BaseLayout pageIndex={0} >
            <Typography variant="h6">Welcome to YTM ROVERS</Typography>
      </BaseLayout>
    </>
  )   
}


